---
- name: install Apache
  hosts: all
  become: yes

  tasks:
  - name : OS Check
    debug: var=ansible_os_family

  - name : Install the latest Nginx package
    apt: name=nginx state=latest update_cache=true
    when: ansible_os_family== "Debian"

  - name : install httpd package
    apt: name=apache2 state=latest update_cache=true
    when: ansible_os_family== "Debian"


